package synapticloop.package.sample;

// - - - - thoughtfully generated by synapticloop gradle-plugin-java-create - - - - 
//             with the use of synapticloop templar templating language
//                        (pluginextension.java.templar)


import java.util.ArrayList;
import java.util.List;


public class TestSamplePluginExtension {
}
