package synapticloop.package.sample;

// - - - - thoughtfully generated by synapticloop gradle-plugin-java-create - - - - 
//             with the use of synapticloop templar templating language
//                           (plugin.java.templar)


import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class TestSamplePlugin implements Plugin<Project> {

	@Override
	public void apply(Project project) {
		project.getExtensions().create("TestSamplePlugin", TestSamplePluginExtension.class);


	}
}
