package synapticloop.package.sample;

// - - - - thoughtfully generated by synapticloop gradle-plugin-java-create - - - - 
//            with the use of synapticloop templar templating language
//                            (task.java.templar)


import org.gradle.api.DefaultTask;
import org.gradle.api.logging.Logger;
import org.gradle.api.tasks.TaskAction;

public class TestSampleTask extends DefaultTask {
	private Logger logger;
	private TestSamplePluginExtension extension;

	public TestSampleTask() {
		setGroup("Sample");
		setDescription("a simple test plugin");

		this.logger = getProject().getLogger();
	}

	@TaskAction
	public void generate() {
		extension = getProject().getExtensions().findByType(TestSamplePluginExtension.class);

		if (extension == null) {
			extension = new TestSamplePluginExtension();
		}

		logger.info("This will only be logged when the task is invoked with the --info command line argument.");
		logger.debug("This will only be logged when the task is invoked with the --debug command line argument.");
		logger.lifecycle("This will be logged as output on standard out.");

	}
}

