package synapticloop.plugin.sample;

// - - - - thoughtfully generated by synapticloop gradle-plugin-java-create - - - - 
//             with the use of synapticloop templar templating language
//                           (plugin.java.templar)


import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class TestSamplePlugin implements Plugin<Project> {
	public static final String PLUGIN_NAME = "testSample";

	@Override
	public void apply(Project project) {
		// Register the plugin extension with the project
		project.getExtensions().create(PLUGIN_NAME, TestSamplePluginExtension.class);

		// Register the plugin task with the project
		project.getTasks().create(PLUGIN_NAME, TestSampleTask.class);
	}
}
