package synapticloop.plugin.sample;

// - - - - thoughtfully generated by synapticloop gradle-plugin-java-create - - - - 
//             with the use of synapticloop templar templating language
//                        (pluginextension.java.templar)


import java.util.ArrayList;
import java.util.List;


public class TestSamplePluginExtension {
	private boolean booleanValue = false;
	private List<String> stringList = new ArrayList<String>();
	private String stringValue = "someString";

	public boolean getBooleanValue() {
		return(this.booleanValue);
	}

	public void setBooleanValue(boolean booleanValue) {
		this.booleanValue = booleanValue;
	}

	public List<String> getStringList() {
		return this.stringList;
	}

	public void setStringList(List<String> stringList) {
		this.stringList = stringList;
	}

	public String getStringValue() {
		return this.stringValue;
	}

	public void setStringValue(String stringValue) {
		this.stringValue = stringValue;
	}
}
